# Generated by Django 4.0.4 on 2022-04-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionmodel',
            old_name='prescription',
            new_name='description',
        ),
    ]
