# Generated by Django 4.0.2 on 2022-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='department',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
