# Generated by Django 4.0.4 on 2022-04-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('', 'Select Medicine Type'), ('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Drops', 'Drops'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Powder', 'Powder'), ('Lotion', 'Lotion'), ('Gel', 'Gel'), ('Aerosols', 'Aerosols'), ('Suspension', 'Suspension'), ('Solution', 'Solution'), ('Inhaler', 'Inhaler')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_details', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('available_quantity', models.IntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generics', models.CharField(blank=True, max_length=255, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('interaction', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('pregnancy_lactation', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('theraputic_class', models.TextField(blank=True, null=True)),
                ('storage', models.TextField(blank=True, null=True)),
                ('pharmaceutical_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='MedicineSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medicine Section',
                'verbose_name_plural': 'Medicine Sections',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Payment Method'), ('Cash on Delivery', 'Cash on Delivery'), ('bKash', 'bKash'), ('Nagad', 'Nagad')], max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Select Status'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine Order',
                'verbose_name_plural': 'Medicine Orders',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_control.medicinemodel')),
                ('medicine_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_control.medicineordermodel')),
            ],
            options={
                'verbose_name': 'Medicine Order Item',
                'verbose_name_plural': 'Medicine Order Items',
            },
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='medicine_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_control.medicinesectionmodel'),
        ),
        migrations.CreateModel(
            name='MedicineCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine Cart',
                'verbose_name_plural': 'Medicine Carts',
            },
        ),
        migrations.CreateModel(
            name='MedicineCartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_control.medicinecartmodel')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_control.medicinemodel')),
            ],
            options={
                'verbose_name': 'Medicine Cart Item',
                'verbose_name_plural': 'Medicine Cart Items',
            },
        ),
    ]
