# Generated by Django 4.0.4 on 2022-04-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(choices=[('', 'Select a District'), ('Bagerhat', 'Bagerhat'), ('Bandarban', 'Bandarban'), ('Barguna', 'Barguna'), ('Barishal', 'Barishal'), ('Bhola', 'Bhola'), ('Bogura', 'Bogura'), ('Brahmanbaria', 'Brahmanbaria'), ('Chandpur', 'Chandpur'), ('Chapainawabganj', 'Chapainawabganj'), ('Chattogram', 'Chattogram'), ('Chuadanga', 'Chuadanga'), ('Cox’s Bazar', 'Cox’s Bazar'), ('Cumilla', 'Cumilla'), ('Dhaka', 'Dhaka'), ('Dinajpur', 'Dinajpur'), ('Faridpur', 'Faridpur'), ('Feni', 'Feni'), ('Gaibandha', 'Gaibandha'), ('Gazipur', 'Gazipur'), ('Gopalganj', 'Gopalganj'), ('Habiganj', 'Habiganj'), ('Jamalpur', 'Jamalpur'), ('Jashore', 'Jashore'), ('Jhalokati', 'Jhalokati'), ('Jhenaidah', 'Jhenaidah'), ('Joypurhat', 'Joypurhat'), ('Khagrachhari', 'Khagrachhari'), ('Khulna', 'Khulna'), ('Kishoreganj', 'Kishoreganj'), ('Kushtia', 'Kushtia'), ('Kurigram', 'Kurigram'), ('Lakshmipur', 'Lakshmipur'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Magura', 'Magura'), ('Manikganj', 'Manikganj'), ('Meherpur', 'Meherpur'), ('Moulvibazar', 'Moulvibazar'), ('Munshiganj', 'Munshiganj'), ('Mymensingh', 'Mymensingh'), ('Naogaon', 'Naogaon'), ('Narayanganj', 'Narayanganj'), ('Narail', 'Narail'), ('Narsingdi', 'Narsingdi'), ('Natore', 'Natore'), ('Netrokona', 'Netrokona'), ('Nilphamari', 'Nilphamari'), ('Noakhali', 'Noakhali'), ('Pabna', 'Pabna'), ('Panchagarh', 'Panchagarh'), ('Patuakhali', 'Patuakhali'), ('Pirojpur', 'Pirojpur'), ('Rajbari', 'Rajbari'), ('Rajshahi', 'Rajshahi'), ('Rangamati', 'Rangamati'), ('Rangpur', 'Rangpur'), ('Satkhira', 'Satkhira'), ('Shariatpur', 'Shariatpur'), ('Sherpur', 'Sherpur'), ('Sirajganj', 'Sirajganj'), ('Sunamganj', 'Sunamganj'), ('Sylhet', 'Sylhet'), ('Tangail', 'Tangail'), ('Thakurgaon', 'Thakurgaon')], max_length=20)),
                ('category', models.CharField(choices=[('Standard', 'Standard'), ('AC', 'AC'), ('Cardiac', 'Cardiac'), ('ICU', 'ICU'), ('Freezer', 'Freezer')], max_length=20)),
                ('driverName', models.CharField(blank=True, max_length=20, null=True)),
                ('driverContact', models.CharField(blank=True, max_length=20, null=True)),
                ('driverEmail', models.EmailField(blank=True, max_length=20, null=True)),
                ('driverAddress', models.CharField(blank=True, max_length=20, null=True)),
                ('driverNID', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('driverLicense', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('driverBloodGroup', models.CharField(blank=True, max_length=20, null=True)),
                ('driverGender', models.CharField(blank=True, max_length=20, null=True)),
                ('driverImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('ambulanceImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('rentInterDivision', models.IntegerField(blank=True, null=True)),
                ('rentIntraDivision', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ambulances',
            },
        ),
        migrations.CreateModel(
            name='BookAmbulanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientContact', models.CharField(max_length=14)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('is_emergency', models.BooleanField(default=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientmodel')),
            ],
            options={
                'verbose_name_plural': 'Booked Ambulances',
            },
        ),
    ]
