# Generated by Django 3.2.5 on 2022-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('driverName', models.CharField(blank=True, max_length=20, null=True)),
                ('driverContact', models.CharField(blank=True, max_length=20, null=True)),
                ('driverEmail', models.EmailField(blank=True, max_length=20, null=True)),
                ('driverAddress', models.CharField(blank=True, max_length=20, null=True)),
                ('driverNID', models.CharField(blank=True, max_length=20, null=True)),
                ('driverLicense', models.CharField(blank=True, max_length=20, null=True)),
                ('driverBloodGroup', models.CharField(blank=True, max_length=20, null=True)),
                ('driverGender', models.CharField(blank=True, max_length=20, null=True)),
                ('driverImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('ambulanceImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('rentInterDivision', models.IntegerField(blank=True, null=True)),
                ('rentIntraDivision', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
