# Generated by Django 3.2.12 on 2022-04-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAmbulanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientContact', models.CharField(max_length=14)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('is_emergency', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientmodel')),
            ],
        ),
    ]
