# Generated by Django 3.2.12 on 2022-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_bookambulancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookambulancemodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookambulancemodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
